
apiVersion: v1
kind: Secret
metadata:
  name: beacon-slack
  creationTimestamp:
data:
  slack_hook_url: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA1NTZEUDlZL0IwMk0zNkNGVEwyL1FCSFRtMk5yTG1QZkhpc01FRXdXa0VyZA=="
